---
- hosts: slaves
  become: yes
  tasks:
  -  name: Download zabbix-release_5.0-1+focal_all.deb
     ansible.builtin.get_url:
        url: https://repo.zabbix.com/zabbix/5.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_5.0-1+focal_all.deb
        dest: /tmp/zabbix-release_5.0-1+focal_all.deb
     when:
        ansible_os_family == "Debian"
  -  name: Install zabbix-release_5.0-1+focal_all.deb on Debian
     ansible.builtin.apt:
        deb: /tmp/zabbix-release_5.0-1+focal_all.deb
        state: present
     when:
        ansible_os_family == "Debian"
  -  name: Update cache on Ubuntu
     apt:
        update_cache=yes
     when:
        ansible_os_family == "Debian"
  -  name: Install zabbix-agent on Ubuntu
     apt:
        name=zabbix-agent
        state=latest
     when:
        ansible_os_family == "Debian"
  -  name: Install the Zabbix RPM repository on RedHat Family
     yum:
        name="https://repo.zabbix.com/zabbix/5.0/rhel/7/x86_64/zabbix-release-5.0-1.el7.noarch.rpm"
        state=present
     when:
        ansible_os_family == "RedHat"         
  -  name: yum clean all on RedHat Family
     ansible.builtin.shell:
        cmd: yum clean all
     when:
        ansible_os_family == "RedHat"
  -  name: Install zabbix-agent on RedHat Family
     yum:
        name=zabbix-agent
        state=latest
     when:
        ansible_os_family == "RedHat"        
